# Generated by Django 5.2.6 on 2025-10-03 06:40

import common.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to=common.utils.storage.lease_document_upload_path),
        ),
        migrations.AddField(
            model_name='lease',
            name='police_verification_file',
            field=models.FileField(blank=True, null=True, upload_to=common.utils.storage.lease_document_upload_path),
        ),
    ]
