# Generated by Django 5.2.6 on 2025-10-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_lease_agreement_file_lease_police_verification_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lease',
            options={'ordering': ['-start_date', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='lease',
            name='unique_active_lease_per_unit',
        ),
    ]
