# Generated by Django 5.2.6 on 2025-10-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_alter_lease_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='deposit_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('adjusted', 'Adjusted'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
