# Generated by Django 5.2.6 on 2025-10-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renter',
            old_name='month_income',
            new_name='monthly_income',
        ),
    ]
