# Generated by Django 5.2.6 on 2025-10-01 15:24

import common.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renters', '0002_rename_month_income_renter_monthly_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='nid_scan',
            field=models.FileField(blank=True, null=True, upload_to=common.utils.storage.renter_nid_upload_path),
        ),
        migrations.AddField(
            model_name='renter',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.storage.renter_profile_upload_path),
        ),
    ]
