# Generated by Django 5.2.6 on 2025-10-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renters', '0003_renter_nid_scan_renter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='renter',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='renter',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='renter',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='renter',
            name='office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='renter',
            name='relation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
