# Generated by Django 5.2.6 on 2025-10-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renters', '0004_alter_renter_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
