# Generated by Django 5.2.6 on 2025-10-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renters', '0005_alter_renter_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='status',
            field=models.CharField(choices=[('prospective', 'Prospective'), ('active', 'Active'), ('former', 'Former')], default='prospective', max_length=20),
        ),
    ]
