# Generated by Django 5.2.6 on 2025-10-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renters', '0006_renter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='notification_preference',
            field=models.CharField(choices=[('none', 'None'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Both')], default='none', help_text='Select how this renter wants to receive notifications', max_length=20),
        ),
    ]
