import io
import os
from decimal import Decimal
from django.conf import settings
from django.core.files.base import ContentFile
from django.db import transaction
from reportlab.lib import colors, styles
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from invoices.models import Invoice
from payments.models import Payment

# -----------------------------
# Helpers
# -----------------------------
DEFAULT_FONT = 'Helvetica'



def currency(value):
    if value is None:
        value = Decimal('0.00')
    if not isinstance(value, Decimal):
        try:
            value = Decimal(value)
        except Exception:
            value = Decimal('0.00')
    return f"{value:,.2f}"

def _header_footer(canvas_obj, doc, unit_name=None):
    canvas_obj.saveState()
    width, height = A4

    # Header
    title = unit_name or 'Building Manager'
    canvas_obj.setFont('Helvetica-Bold', 14)
    canvas_obj.setFillColor(colors.HexColor("#2E4053"))
    canvas_obj.drawCentredString(width / 2.0, height - 40, title)
    canvas_obj.setFont('Helvetica', 9)
    canvas_obj.setFillColor(colors.gray)
    canvas_obj.drawCentredString(width / 2.0, height - 55, "Monthly Invoice")
    canvas_obj.setStrokeColor(colors.lightgrey)
    canvas_obj.setLineWidth(0.5)
    canvas_obj.line(doc.leftMargin, height - 60, width - doc.rightMargin, height - 60)

    # Footer
    canvas_obj.setStrokeColor(colors.lightgrey)
    canvas_obj.line(doc.leftMargin, 40, width - doc.rightMargin, 40)
    canvas_obj.setFont('Helvetica', 8)
    canvas_obj.setFillColor(colors.gray)
    canvas_obj.drawCentredString(width / 2.0, 30, "Generated by Building Manager • Confidential Document")
    canvas_obj.setFont('Helvetica-Oblique', 8)
    canvas_obj.setFillColor(colors.darkgray)
    canvas_obj.drawRightString(width - doc.rightMargin, 30, f"Page {canvas_obj.getPageNumber()}")
    canvas_obj.restoreState()

def generate_invoice_pdf(invoice: Invoice):
    """Generate a PDF invoice with your building/unit/renter info and header/footer."""
    media_root = getattr(settings, "MEDIA_ROOT", None)
    if not media_root:
        raise ValueError("MEDIA_ROOT not configured in settings.")

    folder_path = os.path.join(media_root, 'documents', 'invoices', invoice.invoice_month.strftime('%Y/%m') if invoice.invoice_month else 'misc', f"invoice_{invoice.invoice_number or invoice.id}")
    os.makedirs(folder_path, exist_ok=True)
    filename = f"Invoice-{invoice.invoice_number or invoice.id}.pdf"
    pdf_path = os.path.join(folder_path, filename)

    doc = SimpleDocTemplate(pdf_path, pagesize=A4, rightMargin=50, leftMargin=50, topMargin=80, bottomMargin=60)

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='NormalSmall', fontSize=9, leading=12))
    styles.add(ParagraphStyle(name='HeadingSmall', fontSize=11, leading=14, spaceAfter=6, fontName='Helvetica-Bold'))

    story = []

    # ---------------------------
    # Invoice meta & renter info
    # ---------------------------
    lease = invoice.lease
    renter = lease.renter
    unit = lease.unit

    # Invoice meta
    meta_data = [
        [Paragraph(f"<b>Invoice #</b>", styles['HeadingSmall']), Paragraph(str(invoice.invoice_number), styles['NormalSmall'])],
        [Paragraph(f"<b>Invoice Date</b>", styles['HeadingSmall']), Paragraph(str(invoice.invoice_date), styles['NormalSmall'])],
        [Paragraph(f"<b>Due Date</b>", styles['HeadingSmall']), Paragraph(str(invoice.due_date), styles['NormalSmall'])],
    ]

    renter_data = [
        [Paragraph(f"<b>Bill To:</b>", styles['HeadingSmall'])],
        [Paragraph(renter.full_name, styles['NormalSmall'])],
        [Paragraph(f"Unit: {unit.name}", styles['NormalSmall'])],
        [Paragraph(f"Phone: {renter.phone_number}", styles['NormalSmall'])],
    ]

    header_tbl = Table([[renter_data, meta_data]], colWidths=[300, 170])
    header_tbl.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(header_tbl)
    story.append(Spacer(1,12))

    # ---------------------------
    # Amount table
    # ---------------------------
    total_amount = invoice.amount
    paid_amount = invoice.paid_amount or Decimal("0.00")
    remaining_amount = total_amount - paid_amount

    items = [
        [Paragraph('<b>Description</b>', styles['HeadingSmall']), Paragraph('<b>Amount (BDT)</b>', styles['HeadingSmall'])],
        [Paragraph(invoice.description or 'Monthly Rent', styles['NormalSmall']), Paragraph(currency(total_amount), styles['NormalSmall'])],
        [Paragraph('<b>Paid</b>', styles['NormalSmall']), Paragraph(currency(paid_amount), styles['NormalSmall'])],
        [Paragraph('<b>Remaining</b>', styles['NormalSmall']), Paragraph(currency(remaining_amount), styles['NormalSmall'])],
    ]

    tbl = Table(items, colWidths=[360,110])
    tbl.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f0f0f0')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('ALIGN', (1,1), (-1,-1), 'RIGHT'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
    ]))
    story.append(tbl)
    story.append(Spacer(1,18))

    # -------------------------------
    # NOTES
    # -------------------------------
    status_note = {
        "paid": "This invoice is fully paid.",
        "partially_paid": f"Partial payment received. Remaining due: {currency(remaining_amount)} BDT.",
        "unpaid": f"This invoice is unpaid. Total due: {currency(remaining_amount)} BDT.",
    }.get(invoice.status, "Invoice generated.")

    bullet_notes = [
        "Please pay the rent within 10th of the current month.",
        "Electricity and gas are prepaid; utilities are not included in the rent and will be borne by the renter.",
        "Subletting is not allowed.",
        "No modifications to the unit are allowed without owner's permission.",
        "Any damage caused by the renter must be repaired by the renter.",
        "Security deposit is refundable if rent has been continuously paid until leaving.",
        "Ensure your own safety in the unit; the building owner is not responsible for any event."
    ]

    all_notes = [status_note] + [f"• {n}" for n in bullet_notes]
    note_text = "<br/>".join(all_notes)
    notes_table = Table(
        [[Paragraph(note_text, ParagraphStyle(name="Notes", fontSize=9, leading=12))]],
        colWidths=[500],
        style=[
            ("BOX", (0, 0), (-1, -1), 0.3, colors.grey),
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f9f9f9")),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]
    )
    story.append(notes_table)
    story.append(Spacer(1, 20))

    # -------------------------------
    # SIGNATURE
    # -------------------------------
    signature_tbl = Table(
        [[Paragraph("<b>Authorized Signature</b>", styles["NormalSmall"])], [""]],
        colWidths=[200],
    )
    signature_tbl.setStyle(TableStyle([
        ("LINEABOVE", (0, 1), (0, 1), 0.5, colors.black),
        ("TOPPADDING", (0, 1), (0, 1), 10),
    ]))
    story.append(signature_tbl)

    # Build PDF with header/footer
    doc.build(
        story,
        onFirstPage=lambda c,d: _header_footer(c,d, unit.name),
        onLaterPages=lambda c,d: _header_footer(c,d, unit.name)
    )

    # Save path to model
    invoice.invoice_pdf.name = os.path.relpath(pdf_path, settings.MEDIA_ROOT)
    invoice.save(update_fields=['invoice_pdf'])

    return invoice.invoice_pdf.url


def apply_bulk_payment(lease, amount, method="cash", transaction_reference=None, notes=None):
    """
    Allocate a payment amount to all unpaid/partially paid invoices of a lease (oldest first).
    Returns:
        - List of Payment objects created
        - List of allocation details per invoice: {invoice_id, amount_applied, new_status}
    """
    if amount <= 0:
        raise ValueError("Payment amount must be positive.")

    from django.db.models import Q

    invoices = Invoice.objects.filter(
        lease=lease
    ).exclude(
        Q(status="paid") | Q(invoice_type__in=["security_deposit", "adjustment"])
    ).order_by("invoice_date", "id")
    # chronological order

    payments_created = []
    allocation = []
    remaining_amount = Decimal(amount)

    with transaction.atomic():
        for invoice in invoices:
            if remaining_amount <= 0:
                break

            invoice_balance = invoice.amount - invoice.paid_amount
            if invoice_balance <= 0:
                continue

            pay_amount = min(invoice_balance, remaining_amount)

            payment = Payment.objects.create(
                invoice=invoice,
                lease=lease,
                amount=pay_amount,
                method=method,
                transaction_reference=transaction_reference,
                notes=notes or "",
            )
            payments_created.append(payment)

            # Update invoice paid_amount and status
            invoice.paid_amount += pay_amount
            if invoice.paid_amount >= invoice.amount:
                invoice.status = "paid"
            else:
                invoice.status = "partially_paid"
            invoice.save(update_fields=["paid_amount", "status"])

            # Update lease deposit status if security deposit invoice fully paid
            if invoice.invoice_type == "security_deposit" and lease.deposit_status != "paid":
                lease.deposit_status = "paid"
                lease.save(update_fields=["deposit_status"])

            allocation.append({
                "invoice_id": invoice.id,
                "amount_applied": str(pay_amount),
                "status": invoice.status
            })

            remaining_amount -= pay_amount

    return payments_created, allocation
