# Generated by Django 5.2.6 on 2025-10-01 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_type', models.CharField(choices=[('residential', 'Residential'), ('shop', 'Shop')], max_length=20)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='vacant', max_length=20)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('prepaid_electricity_meter_no', models.CharField(blank=True, max_length=50)),
                ('prepaid_electricity_old_meter_no', models.CharField(blank=True, max_length=50)),
                ('prepaid_electricity_customer_no', models.CharField(blank=True, max_length=50)),
                ('prepaid_gas_meter_customer_code', models.CharField(blank=True, max_length=50)),
                ('prepaid_gas_meter_prepaid_code', models.CharField(blank=True, max_length=50)),
                ('prepaid_gas_meter_no', models.CharField(blank=True, max_length=50)),
                ('prepaid_gas_card_no', models.CharField(blank=True, max_length=50)),
                ('meter_scan_files', models.FileField(blank=True, null=True, upload_to='unit_meters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.floor')),
            ],
        ),
    ]
