# Generated by Django 5.2.6 on 2025-10-01 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='meter_scan_files',
        ),
        migrations.AlterField(
            model_name='unit',
            name='prepaid_electricity_customer_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='prepaid_electricity_meter_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='prepaid_electricity_old_meter_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='prepaid_gas_card_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='prepaid_gas_meter_customer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='prepaid_gas_meter_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='prepaid_gas_meter_prepaid_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], max_length=20),
        ),
        migrations.CreateModel(
            name='UnitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/units/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(choices=[('electricity_meter', 'Electricity Meter'), ('gas_meter', 'Gas Meter'), ('other', 'Other')], max_length=50)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='buildings.unit')),
            ],
        ),
    ]
