# Generated by Django 5.2.6 on 2025-10-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_remove_unit_meter_scan_files_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitDocument',
        ),
    ]
