# Generated by Django 5.2.6 on 2025-10-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
        ('renters', '0006_renter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='error_message',
        ),
        migrations.AddField(
            model_name='notification',
            name='log_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='renters.renter'),
        ),
    ]
