# Generated by Django 5.2.6 on 2025-10-10 10:47

import common.utils.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('renters', '0007_renter_notification_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('utility', 'Utility'), ('repair', 'Repair'), ('other', 'Other')], default='other', max_length=50)),
                ('date', models.DateField()),
                ('is_renter_related', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, help_text='Optional receipt or supporting document.', null=True, upload_to=common.utils.storage.expense_attachment_upload_path)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(blank=True, help_text='Linked renter if this expense is renter-specific.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='renters.renter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
