# Generated by Django 5.2.6 on 2025-10-08 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task_name',
            field=models.CharField(choices=[('GENERATE_INVOICES', 'Generate Invoices'), ('LEASE_REMINDER', 'Lease Reminder'), ('CUSTOM', 'Custom Task')], max_length=255),
        ),
    ]
