# Generated by Django 5.2.6 on 2025-10-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_options_and_more'),
        ('leases', '0001_initial'),
        ('payments', '0002_payment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='leases.lease'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice'),
        ),
    ]
