# Generated by Django 5.2.6 on 2025-10-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date', '-id']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='issue_date',
            new_name='invoice_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
