# Generated by Django 5.2.6 on 2025-10-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
