# Generated by Django 5.2.6 on 2025-10-09 06:02

import common.utils.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_is_final'),
        ('leases', '0004_alter_lease_deposit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_month',
            field=models.DateField(blank=True, help_text='Use first day of month: YYYY-MM-01 for rent invoices', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to=common.utils.storage.invoice_pdf_upload_path),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_type', 'rent')), fields=('lease', 'invoice_month'), name='unique_rent_invoice_per_lease_month'),
        ),
    ]
