# Generated by Django 5.2.6 on 2025-10-01 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0004_delete_unitdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/units/%Y/%m/')),
                ('doc_type', models.CharField(choices=[('electricity_meter', 'Electricity Meter'), ('gas_meter', 'Gas Meter'), ('other', 'Other')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='buildings.unit')),
            ],
        ),
    ]
