# Generated by Django 5.2.6 on 2025-10-01 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_unitdocument_created_at_unitdocument_created_by_and_more'),
        ('renters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/renters/%Y/%m/')),
                ('doc_type', models.CharField(choices=[('nid', 'NID'), ('passport', 'Passport'), ('other', 'Other')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='renters.renter')),
            ],
        ),
    ]
